---
resources:
- name: nginx-release
  type: git
  source:
    uri: git@github.com:mgurke/nginx-release.git
    branch: master
    private_key: ((priv_key))
- name: nginx-pipeline
  type: git
  source:
    uri: git@github.com:mgurke/nginx-pipeline.git
    branch: master
    private_key: ((priv_key))

      

jobs:
- name: create-release
  public: true
  plan:
  - get: nginx-release
    trigger: true
  - get: nginx-pipeline  
    trigger: true
  - task: create-release
    file: nginx-pipeline/tasks/create-release.yml
#    params:
#        BOSH_CLIENT: ((bosh_client))
#        BOSH_CLIENT_SECRET: ((bosh_client_secret))
#        BOSH_ENVIRONMENT: ((bosh_url))
#        BOSH_CA_CERT: "((bosh_ca_cert))"
#    config:
#      platform: linux
#      inputs:
#      - name: nginx-pipeline
#      - name: connect_director