---
resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:mgurke/nginx-release.git
    branch: master
    private_key: |
      



jobs:
  - name: deploy nginx
    plan:
      - get: source-code
      - task: deploy-nginx
        run:
          path: /nginx-release/lifecycle.sh


