---
resources:
- name: nginx-release
  type: git
  source:
    uri: git@github.com:mgurke/nginx-release.git
    branch: master
    private_key: ((priv_key))
- name: nginx-pipeline
  type: git
  source:
    uri: git@github.com:mgurke/nginx-pipeline.git
    branch: master
    private_key: ((priv_key))

      



jobs:
- name: create-release
  public: true
  plan:
  - get: nginx-release
    trigger: true
  - get: nginx-pipeline  
    trigger: true
  - task: hello-world
    config:
      platform: linux
      inputs:
      - name: nginx-pipeline
      image_resource:
        type: docker-image
#  source: {repository: busybox}
        source: {repository: governmentpaas/bosh-cli} 
    
      run:
        path: /bin/bash
        args:
        - -exc
        - |
          echo "Hello Maurice from the other side!"
          bosh vms