---
resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:mgurke/nginx-release.git
    branch: master
    private_key: ((priv_key))
- name: pipeline
  type: git
  source:
    uri: git@github.com:mgurke/nginx-pipeline.git
    branch: master
    private_key: ((priv_key))

      

inputs:
- name: pipeline

jobs:
  - name: deploy nginx
    public: true
    plan:
      - get: source-code
      - get: pipeline
      - task: deploy-nginx
        file: pipeline/create-release.yml