---
resource_types:
- name: keyval
  type: docker-image
  source:
    repository: swce/keyval-resource 


resources:
- name: nginx-release
  type: git
  source:
    uri: git@github.com:mgurke/nginx-release.git
    branch: master
    private_key: ((priv_key))
- name: nginx-pipeline
  type: git
  source:
    uri: git@github.com:mgurke/nginx-pipeline.git
    branch: master
    private_key: ((priv_key))
- name: keyval
  type: keyval

      

jobs:
- name: create-release
  public: true
  plan:
  - get: nginx-release
    trigger: true
  - get: nginx-pipeline  
    trigger: true
  - task: create-release
    file: nginx-pipeline/tasks/create-release.yml
    params:
        BOSH_CLIENT: ((bosh_client))
        BOSH_CLIENT_SECRET: ((bosh_client_secret))
        BOSH_ENVIRONMENT: ((bosh_url))
        BOSH_CA_CERT: "((bosh_ca_cert))"
        BOSH_ALIAS: ((bosh_alias))
        BOSH_IP: ((bosh_ip))
        URL_NGINX_RELEASE: ((nginx-release))
        URL_PCRE_RELEASE: ((pcre-release))
        NGINX_VERSION: ((nginx-version))
        PCRE_VERSION: ((pcre-version))
  - put: keyval
    params:
      file: keyval/keyval.properties

- name: trigger
  public: true
  plan:
  - task: deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: concourse/bosh-cli}
      run:
        path: /bin/bash
        args: 
          - -exec
          - |
            echo "HELLO WORLD"
  