---
platform: linux
inputs:
- name: nginx-pipeline
- name: nginx-release

image_resource:
  type: docker-image
  source: {repository: concourse/bosh-cli} 
run:
  path: nginx-pipeline/tasks/create-release.sh
  args: [nginx-pipeline, nginx-release]