---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/bosh-cli} 

inputs:
- name: nginx-pipeline
- name: nginx-release
- name: tasks


run:
  path: nginx-release/tasks/create-release.sh
  args: [nginx-pipeline, nginx-release]