---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/bosh-cli} 

inputs:

- name: nginx-release
- name: keyval



run:
  path: nginx-pipeline/tasks/deploy-release.sh
  args: [nginx-pipeline, nginx-release]