---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/bosh-cli} 

inputs:
- name: nginx-pipeline
- name: keyval

outputs:
- name: version-tag



run:
  path: nginx-pipeline/tasks/tag-version.sh
  args: [nginx-pipeline, nginx-release, version-tag/version]