---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/bosh-cli} 

inputs:
- name: nginx-pipeline
- name: keyval



run:
  path: nginx-pipeline/tasks/test-deployment.sh
  args: [nginx-pipeline, nginx-release]